site_name: Wildlife Datasets

theme:
  name: "material"
  features:
    - navigation.sections

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - markdown-exec
  - mkdocstrings:
      handlers:
        python:
          paths: [wildlife_datasets]
    
nav:
  - Introduction: index.md  
  - Installation: installation.md
  - Oveview of datasets: datasets.md
  - Tutorials:
    - Getting started: tutorial_datasets.md
    - Testing ML methods: methods.md
    - Recommended datasets: recommended.md
    - Default splits: default_splits.md
  - Advanced:
    - Advanced splits: tutorial_splits.md
    - Dataset representation: dataframe.md
    - Adding new datasets: adding.md
  - Dataset preprocessing:
    - Preprocessing: downloads.md
  - Reference:
    - Datasets: reference_datasets.md
    - Analysis: reference_analysis.md
    - Splits: reference_splits.md
